version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: rr7_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rr7_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Optional lightweight admin UI (uncomment to use)
  # adminer:
  #   image: adminer:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres

volumes:
  pg_data:
